# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('loss-net-device',['core','point-to-point'])
    module.source = [
        'model/loss-net-device.cc',
        'helper/loss-helper.cc',
    ]

    headers = bld(features='ns3header')
    headers.module='loss-net-device'
    headers.source=[
        'model/loss-net-device.h',
        'helper/loss-helper.h',
    ]

    module_test = bld.create_ns3_module_test_library('loss')
    module_test.source = [

    ]
    
    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')
    
    # bld.ns3_python_bindings()